template1:
  assigned_staff: darrenho.2019@scis.smu.edu.sg
  customer: Blizzard
  customer_email: darkdrium94@gmail.com
  customer_website: http://www.blizzard.com
  default_mark_up_pct: 10
  rfq_folder: C:\Users\Darren Ho\Documents\GitHub\fyp\aqs_bot\parts_extraction\input\rfq
  archive_folder: C:\Users\Darren Ho\Documents\GitHub\fyp\aqs_bot\parts_extraction\input\archive
  unprocessed_folder: C:\Users\Darren Ho\Documents\GitHub\fyp\aqs_bot\parts_extraction\input\unprocessed
  rfq_to_db_mapping:
    level: Level
    part_no: Component number
    description: Object description
    qty: Quantity
    uom: Un